import torch
import torch.nn as nn
import torch.optim as optim
from collections import deque

from generator.generator_network import MapEditorActorCritic
from generator.history_encoder import HistoryEncoder
import torch.nn.functional as F

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


class GeneratorPPO:
    """
    PPO-based Generator with a learnable History Encoder.
    """

    def __init__(
        self,
        his_emb_dim=16,
        context_dim=64,
        lr_actor=1e-4, # [TUNED] 3e-4 -> 1e-4: Calm down. Fine-tune instead of jumping.
        lr_critic=3e-4,
        gamma=0.99,
        K_epochs=10,   # Keep K_epochs=10 high to learn efficiently from safe steps
        eps_clip=0.2,
        entropy_coef=0.02,
        entropy_coef_start=None,
        entropy_coef_end=None,
        entropy_anneal_iters=0,
        buffer_window_rounds=1,
        update_every_rounds=1,
        num_actions=11,
        # ratio=0.25, # removed
        top_k_features=16,
        ablation_type="none",
        env_type="minigrid",
        initial_edit_ratio=0.3,
        initial_inventory_edit_ratio=0.0,
        edit_action_group_sizes=None,

    ):
        self.gamma = gamma
        self.eps_clip = eps_clip
        self.K_epochs = int(K_epochs)
        self.entropy_coef = entropy_coef
        self.entropy_coef_start = float(entropy_coef if entropy_coef_start is None else entropy_coef_start)
        self.entropy_coef_end = float(entropy_coef if entropy_coef_end is None else entropy_coef_end)
        self.entropy_anneal_iters = max(0, int(entropy_anneal_iters))
        self.buffer_window_rounds = max(1, int(buffer_window_rounds))
        # A rollout is generated by policy_old.  Keep that policy frozen until
        # all rounds in an update batch have been collected.
        self.update_every_rounds = max(1, int(update_every_rounds))
        self.context_dim = context_dim
        self.env_type = str(env_type).lower()
        # self.ratio = ratio # removed
        self.top_k_features = top_k_features
        self.is_bipedal = (self.env_type == "bipedalwalker")
        self.is_minigrid = (self.env_type == "minigrid")
        self.policy_context_dim = (
            context_dim
            if self.is_bipedal or self.is_minigrid
            else context_dim * 2
        )

        # history encoder
        

        # === Networks ===
        if self.is_minigrid:
            # Construct the encoder for every MiniGrid ablation so removing
            # history does not shift the RNG stream used to initialize the
            # shared actor/critic. The no-history run then drops the encoder.
            encoder = HistoryEncoder(
                context_dim=context_dim,
                emb_dim=his_emb_dim,
                env_type=env_type,
            ).to(device)
            self.encoder = None if ablation_type == "no_history" else encoder
        elif ablation_type == "no_history":
            self.encoder = None
        else:
            self.encoder = HistoryEncoder(
                context_dim=context_dim,
                emb_dim=his_emb_dim,
                env_type=env_type,
            ).to(device)

        policy_ablation_type = (
            "none" if self.is_minigrid and ablation_type == "no_history"
            else ablation_type
        )

        self.policy = MapEditorActorCritic(
            num_actions=num_actions,
            context_dim=self.policy_context_dim,
            ablation_type=policy_ablation_type,
            env_type=env_type,
            initial_edit_ratio=initial_edit_ratio,
            initial_inventory_edit_ratio=initial_inventory_edit_ratio,
            edit_action_group_sizes=edit_action_group_sizes,
        ).to(device)

        self.policy_old = MapEditorActorCritic(
            num_actions=num_actions,
            context_dim=self.policy_context_dim,
            ablation_type=policy_ablation_type,
            env_type=env_type,
            initial_edit_ratio=initial_edit_ratio,
            initial_inventory_edit_ratio=initial_inventory_edit_ratio,
            edit_action_group_sizes=edit_action_group_sizes,
        ).to(device)

        self.policy_old.load_state_dict(self.policy.state_dict())

        # === Optimizer (encoder + policy) ===
        optim_params = []

        if self.encoder is not None:
            optim_params.append(
                {"params": self.encoder.parameters(), "lr": lr_actor}
            )

        optim_params += [
            {"params": self.policy.stem.parameters(), "lr": lr_actor},
            {"params": self.policy.res_blocks.parameters(), "lr": lr_actor},
            {"params": self.policy.emb_obj.parameters(), "lr": lr_actor},
            {"params": self.policy.emb_color.parameters(), "lr": lr_actor},
            {"params": self.policy.emb_state.parameters(), "lr": lr_actor},
            {"params": self.policy.actor.parameters(), "lr": lr_actor},
            {"params": self.policy.stats_actor.parameters(), "lr": lr_actor},
            {"params": self.policy.inventory_actor.parameters(), "lr": lr_actor},
            {"params": self.policy.critic.parameters(), "lr": lr_critic},
        ]
        if self.policy.history_fusion is not None:
            optim_params.extend([
                {"params": self.policy.history_fusion.parameters(), "lr": lr_actor},
                {"params": self.policy.history_type_actor.parameters(), "lr": lr_actor},
            ])

        self.optimizer = optim.Adam(optim_params)

        self.mse = nn.MSELoss()

        # === PPO buffer with a consistent per-sample layout ===
        self.buffer = {
            "curr_map": [],
            "prev_map": [],
            "prev_heat": [],
            "mask": [],
            "action": [],         # Terrain actions (grid)
            "logprob": [],        # Terrain logprobs (summed grid)
            "stats_action": [],   # Inventory actions (vector)
            "stats_logprob": [],  # Inventory logprobs (summed vector)
            "value": [],
            "reward": [],
            "topk_mask": [],
            "location_order": [],
            "stats_topk_mask": [],
            "stats_heat": [],     # Inventory error history [1, 16]
        }
        self.last_mean_reward = 0.0
        self.last_entropy_coef = float(self.entropy_coef_start)
        self.round_lengths = deque()
        self.current_round_count = 0
        self.last_diagnostics = self._empty_diagnostics()

    @staticmethod
    def _empty_diagnostics():
        """Diagnostics for the most recent update attempt.

        Values remain serializable so callers can place them directly in their
        experiment logs without changing the existing ``update`` return tuple.
        """
        return {
            "updated": False,
            "sample_count": 0,
            "round_count": 0,
            "policy_loss": 0.0,
            "value_loss": 0.0,
            "entropy_loss": 0.0,
            "total_loss": 0.0,
            "initial_logprob_max_error": 0.0,
            "ratio_mean": 1.0,
            "ratio_min": 1.0,
            "ratio_max": 1.0,
            "approx_kl": 0.0,
            "clip_fraction": 0.0,
            "reward_std": 0.0,
            "advantage_std": 0.0,
            "preclip_grad_norm": 0.0,
            "parameter_delta": 0.0,
        }

    def _parameter_snapshot(self):
        return [
            parameter.detach().clone()
            for group in self.optimizer.param_groups
            for parameter in group["params"]
            if parameter.requires_grad
        ]

    def _parameter_delta(self, before):
        squared_delta = 0.0
        parameters = [
            parameter
            for group in self.optimizer.param_groups
            for parameter in group["params"]
            if parameter.requires_grad
        ]
        for previous, parameter in zip(before, parameters):
            squared_delta += (parameter.detach().float() - previous.float()).pow(2).sum().item()
        return squared_delta ** 0.5

    def _gradient_norm(self):
        """Return the joint L2 norm before gradient clipping."""
        squared_norm = 0.0
        for group in self.optimizer.param_groups:
            for parameter in group["params"]:
                if parameter.grad is not None:
                    squared_norm += parameter.grad.detach().float().pow(2).sum().item()
        return squared_norm ** 0.5

    def _get_entropy_coef(self, iteration=None):
        if iteration is None or self.entropy_anneal_iters <= 0:
            return float(self.entropy_coef)
        if iteration >= self.entropy_anneal_iters:
            return float(self.entropy_coef_end)

        progress = float(iteration) / float(max(self.entropy_anneal_iters, 1))
        return float(
            self.entropy_coef_start
            + (self.entropy_coef_end - self.entropy_coef_start) * progress
        )

    # ------------------------------------------------------------------
    # Context
    # ------------------------------------------------------------------
    def _compute_global_context_dual(self, prev_map, terrain_heat, stats_heat, top_k_features=None):
        """
        Aggregate spatial failure features and inventory failure features.
        Crafter keeps both:
        - local per-sample history context
        - global batch summary context

        MiniGrid keeps only its per-sample semantic context. Broadcasting a
        batch-wise max makes every generated map chase the same dominant
        pattern and is unnecessary once absolute coordinates are removed.
        """
        top_k_features = self.top_k_features if top_k_features is None else int(top_k_features)
        # Use the HistoryEncoder to extract per-sample failure features.
        ctx = self.encoder(prev_map, terrain_heat, stats_heat) # [B, context_dim]

        if self.is_bipedal or self.is_minigrid:
            return F.normalize(ctx, p=2, dim=1)
        
        local_ctx = F.normalize(ctx, p=2, dim=1)

        # Aggregate across the batch with max pooling.
        v_ctx, _ = torch.max(ctx, dim=0, keepdim=True) # [1, context_dim]

        # Keep only the most salient features via top-k sparsification.
        if v_ctx.size(1) > top_k_features:
            top_val, _ = torch.topk(v_ctx, k=top_k_features, dim=1)
            min_val = top_val[:, -1:]
            mask = (v_ctx >= min_val).float()
            v_ctx = v_ctx * mask

        # Normalize feature magnitudes.
        global_ctx = F.normalize(v_ctx, p=2, dim=1)
        global_ctx = global_ctx.expand(local_ctx.size(0), -1)
        return torch.cat([local_ctx, global_ctx], dim=1)

    # ------------------------------------------------------------------
    # Rollout
    # ------------------------------------------------------------------
    @torch.no_grad()
    def select_action(self, base_map, prev_data, mask, max_edits_layout, max_edits_stats):
        B = base_map.size(0)
        if self.encoder is None:   
            ctx = None
            global_ctx = None
            phs = None
        else:
            if prev_data is None:
                # Initial state: empty map, empty terrain heatmap, empty inventory heatmap.
                H, W = base_map.size(2), base_map.size(3)
                # pm: prev_map, pht: prev_heat_terrain, phs: prev_heat_stats
                pm = torch.zeros((1, 3, H, W), device=device)
                feedback_channels = 2 if self.env_type == "minigrid" else 1
                pht = torch.zeros((1, feedback_channels, H, W), device=device)
                phs = None if self.env_type == "minigrid" else torch.zeros(
                    (1, 26 if self.env_type == "bipedalwalker" else 16), device=device
                )
                global_ctx = self._compute_global_context_dual(pm, pht, phs)
            else:
                if len(prev_data) == 2:
                    pm, pht = prev_data
                    phs = None
                else:
                    pm, pht, phs = prev_data
                global_ctx = self._compute_global_context_dual(pm, pht, phs)
            if global_ctx.size(0) == B:
                ctx = global_ctx
            else:
                ctx = global_ctx.repeat(B, 1)
            if phs is not None and phs.size(0) == 1 and B > 1:
                phs = phs.repeat(B, 1)

        (
            action, stats_act, map_logp, location_logp, stats_logp, value,
            topk_mask, location_order, topk_stats_mask,
        ) = self.policy_old.act(
            base_map, ctx, mask, max_edits_layout, max_stats_edit_ratio=max_edits_stats, stats_heat=phs
        )

        # The fixed-budget MiniGrid action has two learned factors: the
        # ordered location set and the categorical type at each location.
        total_logprob = map_logp.sum(dim=(1, 2)) + location_logp + stats_logp
        return (
            action, stats_act, total_logprob, value, topk_mask,
            location_order, topk_stats_mask, global_ctx,
        )

    # ------------------------------------------------------------------
    # Buffer
    # ------------------------------------------------------------------
    def save_buffer(
        self, curr_map, prev_data, mask, action, stats_action, logprob, value,
        reward, topk_mask, location_order, stats_topk_mask,
    ):
        self.buffer["curr_map"].append(curr_map.cpu())
        self.buffer["mask"].append(mask.cpu())
        self.buffer["action"].append(action.cpu())
        self.buffer["stats_action"].append(stats_action.cpu())
        self.buffer["logprob"].append(logprob.cpu())
        self.buffer["value"].append(value.cpu())
        self.buffer["reward"].append(float(reward))
        self.buffer["topk_mask"].append(topk_mask.cpu())
        self.buffer["location_order"].append(location_order.cpu())
        self.buffer["stats_topk_mask"].append(stats_topk_mask.cpu())

        if prev_data is None:
            B, _, H, W = curr_map.shape
            self.buffer["prev_map"].append(torch.zeros((B, 3, H, W)))
            feedback_channels = 2 if self.env_type == "minigrid" else 1
            self.buffer["prev_heat"].append(
                torch.zeros((B, feedback_channels, H, W))
            )
            stats_dim = 26 if self.env_type == "bipedalwalker" else 16
            self.buffer["stats_heat"].append(torch.zeros((B, stats_dim)))
        else:
            if len(prev_data) == 2:
                pm, pht = prev_data
                phs = None
            else:
                pm, pht, phs = prev_data
            self.buffer["prev_map"].append(pm.cpu())
            # We rename prev_heat internally to match dual streams
            self.buffer["prev_heat"].append(pht.cpu())
            if phs is None:
                B = pm.size(0)
                stats_dim = 26 if self.env_type == "bipedalwalker" else 16
                self.buffer["stats_heat"].append(torch.zeros((B, stats_dim)))
            else:
                self.buffer["stats_heat"].append(phs.cpu())
        self.current_round_count += 1

    def clear_buffer(self):
        for k in self.buffer:
            self.buffer[k].clear()
        self.round_lengths.clear()
        self.current_round_count = 0

    def _trim_buffer_to_recent_rounds(self):
        while len(self.round_lengths) > self.buffer_window_rounds:
            remove_n = int(self.round_lengths.popleft())
            if remove_n <= 0:
                continue
            for k in self.buffer:
                if remove_n >= len(self.buffer[k]):
                    self.buffer[k].clear()
                else:
                    del self.buffer[k][:remove_n]

    # ------------------------------------------------------------------
    # PPO Update
    # ------------------------------------------------------------------
    def update(self, iteration=None):
        """Update from complete, on-policy rollout rounds.

        The public return value remains ``(loss, entropy)``.  Detailed values
        are exposed through ``last_diagnostics`` so existing callers do not
        need to change when diagnostic logging is enabled.
        """
        self.last_diagnostics = self._empty_diagnostics()
        if len(self.buffer["curr_map"]) == 0:
            print("[GeneratorPPO] Warning: Buffer is empty, skipping update.")
            return 0.0, 0.0

        if self.current_round_count > 0:
            self.round_lengths.append(self.current_round_count)
            self.current_round_count = 0

        round_count = len(self.round_lengths)
        sample_count = len(self.buffer["reward"])
        self.last_diagnostics.update({
            "sample_count": sample_count,
            "round_count": round_count,
        })
        if round_count < self.update_every_rounds:
            # policy_old remains frozen while this rollout batch is assembled.
            return 0.0, 0.0

        # An update consumes all retained samples.  Under normal operation this
        # is exactly update_every_rounds rounds; retaining extras would mix
        # samples with a policy that will be changed by this update.
        if round_count != self.update_every_rounds:
            raise RuntimeError(
                "GeneratorPPO received more rollout rounds than update_every_rounds "
                f"({round_count} > {self.update_every_rounds})."
            )

        raw_rewards = torch.tensor(self.buffer["reward"], device=device)
        self.last_mean_reward = raw_rewards.mean().item()
        current_entropy_coef = self._get_entropy_coef(iteration)
        self.last_entropy_coef = current_entropy_coef
        print(f"[GeneratorPPO] Mean Reward: {self.last_mean_reward:.4f}")
        print(f"[GeneratorPPO] Entropy Coef: {current_entropy_coef:.4f}")
        print(
            f"[GeneratorPPO] Updating {round_count} round(s), {sample_count} samples"
        )

        rewards = raw_rewards.clone()
        reward_std = rewards.std(unbiased=False).item() if len(rewards) > 1 else 0.0
        if len(rewards) > 1 and reward_std > 1e-4:
            rewards = (rewards - rewards.mean()) / (rewards.std() + 1e-8)

        curr_map = torch.cat(self.buffer["curr_map"]).to(device)
        mask = torch.cat(self.buffer["mask"]).to(device)
        action = torch.cat(self.buffer["action"]).to(device)
        stats_action = torch.cat(self.buffer["stats_action"]).to(device)
        old_logprob = torch.cat(self.buffer["logprob"]).to(device)
        old_value = torch.cat(self.buffer["value"]).to(device).reshape(-1)
        topk_mask = torch.cat(self.buffer["topk_mask"]).to(device)
        location_order = torch.cat(self.buffer["location_order"]).to(device)
        stats_topk_mask = torch.cat(self.buffer["stats_topk_mask"]).to(device)
        prev_map = torch.cat(self.buffer["prev_map"]).to(device)
        prev_heat_terrain = torch.cat(self.buffer["prev_heat"]).to(device)
        prev_heat_stats = torch.cat(self.buffer["stats_heat"]).to(device)

        advantages = rewards - old_value.detach()
        advantage_std = advantages.std(unbiased=False).item() if len(advantages) > 1 else 0.0
        if len(advantages) > 1 and advantage_std > 1e-4:
            advantages = (advantages - advantages.mean()) / (advantages.std() + 1e-8)

        parameter_before = self._parameter_snapshot()
        last_metrics = None
        initial_logprob_max_error = 0.0
        for epoch in range(self.K_epochs):
            # Evaluate each rollout round with the same batch shape used when
            # its log-probability was collected. This avoids harmless but
            # measurable batch-size-dependent floating-point differences in
            # convolution kernels when update_every_rounds > 1.
            round_ranges = []
            offset = 0
            if self.is_minigrid:
                for round_length in self.round_lengths:
                    end = offset + int(round_length)
                    round_ranges.append((offset, end))
                    offset = end
            if not round_ranges or offset != curr_map.size(0):
                round_ranges = [(0, curr_map.size(0))]

            eval_parts = []
            entropy_parts = []
            for start, end in round_ranges:
                if self.encoder is None:
                    ctx_part = None
                else:
                    ctx_part = self._compute_global_context_dual(
                        prev_map[start:end],
                        prev_heat_terrain[start:end],
                        prev_heat_stats[start:end],
                    )
                    if ctx_part.size(0) != end - start:
                        ctx_part = ctx_part.repeat(end - start, 1)

                eval_parts.append(
                    self.policy.evaluate(
                        curr_map[start:end],
                        ctx_part,
                        (action[start:end], stats_action[start:end]),
                        mask[start:end],
                        target_topk_mask=topk_mask[start:end],
                        target_location_order=location_order[start:end],
                        target_stats_topk_mask=stats_topk_mask[start:end],
                        stats_heat=prev_heat_stats[start:end],
                    )
                )
                entropy_parts.append(eval_parts[-1][-1])

            logp_terrain = torch.cat([part[0] for part in eval_parts], dim=0)
            logp_location = torch.cat([part[1] for part in eval_parts], dim=0)
            logp_stats = torch.cat([part[2] for part in eval_parts], dim=0)
            value = torch.cat([part[3] for part in eval_parts], dim=0)
            entropy = sum(
                part * (end - start)
                for part, (start, end) in zip(entropy_parts, round_ranges)
            ) / max(curr_map.size(0), 1)
            total_logp = logp_terrain.sum(dim=(1, 2)) + logp_location + logp_stats
            value = value.reshape(-1)
            logprob_delta = total_logp - old_logprob.detach()
            if epoch == 0:
                # Validate the actual on-policy invariant: the probability
                # recomputed before the first optimizer step must match the
                # value saved during rollout. Comparing policy and policy_old
                # on one newly-computed context would hide context drift.
                initial_logprob_max_error = torch.abs(
                    total_logp.detach() - old_logprob.detach()
                ).max().item()
            ratio = torch.exp(logprob_delta)
            surr1 = ratio * advantages
            surr2 = torch.clamp(ratio, 1 - self.eps_clip, 1 + self.eps_clip) * advantages
            loss_policy = -torch.min(surr1, surr2).mean()
            loss_value = 0.5 * self.mse(value, rewards)
            loss_entropy = -current_entropy_coef * entropy.mean()
            total_loss = loss_policy + loss_value + loss_entropy

            if not torch.isfinite(total_loss):
                print(f"[GeneratorPPO] Warning: non-finite loss in epoch {epoch}; clearing rollout.")
                self.clear_buffer()
                return 0.0, 0.0

            self.optimizer.zero_grad()
            total_loss.backward()
            preclip_grad_norm = self._gradient_norm()
            torch.nn.utils.clip_grad_norm_(self.policy.parameters(), 0.5)
            if self.encoder is not None:
                torch.nn.utils.clip_grad_norm_(self.encoder.parameters(), 0.5)
            self.optimizer.step()

            last_metrics = {
                "policy_loss": loss_policy.item(),
                "value_loss": loss_value.item(),
                "entropy_loss": loss_entropy.item(),
                "total_loss": total_loss.item(),
                "ratio_mean": ratio.mean().item(),
                "ratio_min": ratio.min().item(),
                "ratio_max": ratio.max().item(),
                "approx_kl": (-logprob_delta).mean().item(),
                "clip_fraction": (torch.abs(ratio - 1.0) > self.eps_clip).float().mean().item(),
                "preclip_grad_norm": preclip_grad_norm,
            }
        parameter_delta = self._parameter_delta(parameter_before)
        self.policy_old.load_state_dict(self.policy.state_dict())
        self.clear_buffer()

        self.last_diagnostics.update(last_metrics)
        self.last_diagnostics.update({
            "updated": True,
            "sample_count": sample_count,
            "round_count": round_count,
            "reward_std": reward_std,
            "advantage_std": advantage_std,
            "parameter_delta": parameter_delta,
            "initial_logprob_max_error": initial_logprob_max_error,
        })
        return last_metrics["total_loss"], entropy.mean().item()

    # ------------------------------------------------------------------
    # Save / Load
    # ------------------------------------------------------------------
    def save(self, path):
        save_dict = {"policy": self.policy.state_dict()}
        if self.encoder is not None:
            save_dict["encoder"] = self.encoder.state_dict()
        torch.save(save_dict, path)

    def load(self, path):
        ckpt = torch.load(path, map_location=device)
        self.policy.load_state_dict(ckpt["policy"])
        self.policy_old.load_state_dict(ckpt["policy"])
        if self.encoder is not None and "encoder" in ckpt:
            self.encoder.load_state_dict(ckpt["encoder"])
