import torch
import torch.nn as nn
import torch.optim as optim
from torch.distributions import Categorical
from collections import deque

from generator.generator_network import MapEditorActorCritic
from generator.history_encoder import HistoryEncoder
import torch.nn.functional as F

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


class GeneratorPPO:
    """
    PPO-based Generator with a learnable History Encoder.
    """

    def __init__(
        self,
        his_emb_dim=16,
        context_dim=64,
        lr_actor=1e-4, # [TUNED] 3e-4 -> 1e-4: Calm down. Fine-tune instead of jumping.
        lr_critic=3e-4,
        gamma=0.99,
        K_epochs=10,   # Keep K_epochs=10 high to learn efficiently from safe steps
        eps_clip=0.2,
        entropy_coef=0.02,
        entropy_coef_start=None,
        entropy_coef_end=None,
        entropy_anneal_iters=0,
        buffer_window_rounds=1,
        update_every_rounds=1,
        num_actions=11,
        # ratio=0.25, # removed
        ablation_type="none",
        env_type="minigrid",
        initial_edit_ratio=0.3,
        initial_inventory_edit_ratio=0.0,
        edit_action_group_sizes=None,
        crafter_credit_mode="joint",
        warmup_iterations=0,

    ):
        self.gamma = gamma
        self.eps_clip = eps_clip
        self.K_epochs = int(K_epochs)
        self.entropy_coef = entropy_coef
        self.entropy_coef_start = float(entropy_coef if entropy_coef_start is None else entropy_coef_start)
        self.entropy_coef_end = float(entropy_coef if entropy_coef_end is None else entropy_coef_end)
        self.entropy_anneal_iters = max(0, int(entropy_anneal_iters))
        self.buffer_window_rounds = max(1, int(buffer_window_rounds))
        # A rollout is generated by policy_old.  Keep that policy frozen until
        # all rounds in an update batch have been collected.
        self.update_every_rounds = max(1, int(update_every_rounds))
        self.context_dim = context_dim
        self.env_type = str(env_type).lower()
        if crafter_credit_mode not in ("joint", "split", "split_balanced_global"):
            raise ValueError(
                "crafter_credit_mode must be 'joint', 'split', or 'split_balanced_global'"
            )
        self.crafter_credit_mode = crafter_credit_mode
        self.warmup_iterations = max(0, int(warmup_iterations))
        # self.ratio = ratio # removed
        self.is_bipedal = (self.env_type == "bipedalwalker")
        self.is_minigrid = (self.env_type == "minigrid")
        self.policy_context_dim = context_dim

        # history encoder
        

        # === Networks ===
        if self.is_minigrid:
            # Construct the encoder for every MiniGrid ablation so removing
            # history does not shift the RNG stream used to initialize the
            # shared actor/critic. The no-history run then drops the encoder.
            encoder = HistoryEncoder(
                context_dim=context_dim,
                emb_dim=his_emb_dim,
                env_type=env_type,
            ).to(device)
            self.encoder = None if ablation_type == "no_history" else encoder
        elif ablation_type == "no_history":
            self.encoder = None
        else:
            self.encoder = HistoryEncoder(
                context_dim=context_dim,
                emb_dim=his_emb_dim,
                env_type=env_type,
            ).to(device)

        policy_ablation_type = (
            "none" if self.is_minigrid and ablation_type == "no_history"
            else ablation_type
        )

        self.policy = MapEditorActorCritic(
            num_actions=num_actions,
            context_dim=self.policy_context_dim,
            ablation_type=policy_ablation_type,
            env_type=env_type,
            initial_edit_ratio=initial_edit_ratio,
            initial_inventory_edit_ratio=initial_inventory_edit_ratio,
            edit_action_group_sizes=edit_action_group_sizes,
        ).to(device)

        self.policy_old = MapEditorActorCritic(
            num_actions=num_actions,
            context_dim=self.policy_context_dim,
            ablation_type=policy_ablation_type,
            env_type=env_type,
            initial_edit_ratio=initial_edit_ratio,
            initial_inventory_edit_ratio=initial_inventory_edit_ratio,
            edit_action_group_sizes=edit_action_group_sizes,
        ).to(device)

        self.policy_old.load_state_dict(self.policy.state_dict())

        # === Optimizer (encoder + policy) ===
        optim_params = []

        if self.encoder is not None:
            optim_params.append(
                {"params": self.encoder.parameters(), "lr": lr_actor}
            )

        optim_params += [
            {"params": self.policy.stem.parameters(), "lr": lr_actor},
            {"params": self.policy.res_blocks.parameters(), "lr": lr_actor},
            {"params": self.policy.emb_obj.parameters(), "lr": lr_actor},
            {"params": self.policy.emb_color.parameters(), "lr": lr_actor},
            {"params": self.policy.emb_state.parameters(), "lr": lr_actor},
            {"params": self.policy.actor.parameters(), "lr": lr_actor},
            {"params": self.policy.stats_actor.parameters(), "lr": lr_actor},
            {"params": self.policy.inventory_actor.parameters(), "lr": lr_actor},
            {"params": self.policy.critic.parameters(), "lr": lr_critic},
        ]
        if self.policy.history_fusion is not None:
            optim_params.extend([
                {"params": self.policy.history_fusion.parameters(), "lr": lr_actor},
                {"params": self.policy.history_type_actor.parameters(), "lr": lr_actor},
            ])

        self.optimizer = optim.Adam(optim_params)

        self.mse = nn.MSELoss()

        # === PPO buffer with a consistent per-sample layout ===
        self.buffer = {
            "curr_map": [],
            "prev_map": [],
            "prev_heat": [],
            "mask": [],
            "action": [],         # Terrain actions (grid)
            "logprob": [],        # Terrain logprobs (summed grid)
            "stats_action": [],   # Inventory actions (vector)
            "stats_logprob": [],  # Inventory logprobs (summed vector)
            "value": [],
            "reward": [],
            "layout_reward": [],
            "stage_reward": [],
            "stage_logprob": [],
            "topk_mask": [],
            "location_order": [],
            "stats_topk_mask": [],
            "stats_heat": [],     # Inventory error history [1, 16]
        }
        self.last_mean_reward = 0.0
        self.last_entropy_coef = float(self.entropy_coef_start)
        self.round_lengths = deque()
        self.current_round_count = 0
        self._shared_actor_gradient_conflict_updates = 0
        self._shared_actor_gradient_measure_count = 0
        self.last_diagnostics = self._empty_diagnostics()

    @staticmethod
    def _empty_diagnostics():
        """Diagnostics for the most recent update attempt.

        Values remain serializable so callers can place them directly in their
        experiment logs without changing the existing ``update`` return tuple.
        """
        return {
            "updated": False,
            "sample_count": 0,
            "round_count": 0,
            "policy_loss": 0.0,
            "value_loss": 0.0,
            "entropy_loss": 0.0,
            "total_loss": 0.0,
            "initial_logprob_max_error": 0.0,
            "initial_layout_logprob_max_error": 0.0,
            "initial_stage_logprob_max_error": 0.0,
            "layout_policy_loss": 0.0,
            "stage_policy_loss": 0.0,
            "stage_reward_mean": 0.0,
            "stage_reward_std": 0.0,
            "shared_actor_gradient_cosine": float("nan"),
            "shared_actor_gradient_conflict": float("nan"),
            "shared_actor_gradient_conflict_ratio": float("nan"),
            "shared_layout_gradient_norm": float("nan"),
            "shared_stage_gradient_norm": float("nan"),
            "stage_head_policy_gradient_norm": float("nan"),
            "stage_head_parameter_delta": float("nan"),
            "stage_policy_kl_pre_post": float("nan"),
            "stage_entropy_pre": float("nan"),
            "stage_entropy_post": float("nan"),
            "ratio_mean": 1.0,
            "ratio_min": 1.0,
            "ratio_max": 1.0,
            "approx_kl": 0.0,
            "clip_fraction": 0.0,
            "reward_std": 0.0,
            "advantage_std": 0.0,
            "preclip_grad_norm": 0.0,
            "parameter_delta": 0.0,
        }

    def _parameter_snapshot(self):
        return [
            parameter.detach().clone()
            for group in self.optimizer.param_groups
            for parameter in group["params"]
            if parameter.requires_grad
        ]

    def _parameter_delta(self, before):
        squared_delta = 0.0
        parameters = [
            parameter
            for group in self.optimizer.param_groups
            for parameter in group["params"]
            if parameter.requires_grad
        ]
        for previous, parameter in zip(before, parameters):
            squared_delta += (parameter.detach().float() - previous.float()).pow(2).sum().item()
        return squared_delta ** 0.5

    def _gradient_norm(self):
        """Return the joint L2 norm before gradient clipping."""
        squared_norm = 0.0
        for group in self.optimizer.param_groups:
            for parameter in group["params"]:
                if parameter.grad is not None:
                    squared_norm += parameter.grad.detach().float().pow(2).sum().item()
        return squared_norm ** 0.5

    def _crafter_shared_actor_parameters(self):
        """Parameters used by both Crafter layout and stage policy losses."""
        shared = []
        seen = set()
        modules = (
            getattr(self.policy, name, None)
            for name in ("emb_obj", "emb_color", "emb_state", "stem", "res_blocks", "history_fusion")
        )
        if self.encoder is not None:
            modules = (*modules, self.encoder)
        for module in modules:
            if module is None:
                continue
            for parameter in module.parameters():
                if parameter.requires_grad and id(parameter) not in seen:
                    shared.append(parameter)
                    seen.add(id(parameter))
        return shared

    @staticmethod
    def _shared_gradient_similarity(layout_grads, stage_grads):
        """Return cosine and norms over parameters receiving both actor gradients."""
        paired = [
            (layout.detach().reshape(-1), stage.detach().reshape(-1))
            for layout, stage in zip(layout_grads, stage_grads)
            if layout is not None and stage is not None
        ]
        if not paired:
            return float("nan"), float("nan"), float("nan")
        layout_vector = torch.cat([pair[0] for pair in paired])
        stage_vector = torch.cat([pair[1] for pair in paired])
        layout_norm = torch.linalg.vector_norm(layout_vector)
        stage_norm = torch.linalg.vector_norm(stage_vector)
        norm_product = layout_norm * stage_norm
        if not torch.isfinite(norm_product) or norm_product.item() <= 1e-12:
            return float("nan"), float(layout_norm.item()), float(stage_norm.item())
        cosine = torch.dot(layout_vector, stage_vector) / norm_product
        return (
            float(cosine.clamp(-1.0, 1.0).item()),
            float(layout_norm.item()),
            float(stage_norm.item()),
        )

    @staticmethod
    def _gradient_list_norm(gradients):
        squared_norm = sum(
            gradient.detach().float().pow(2).sum().item()
            for gradient in gradients
            if gradient is not None
        )
        return squared_norm ** 0.5

    @staticmethod
    def _parameter_list_delta(parameters, before):
        squared_delta = sum(
            (parameter.detach().float() - previous.float()).pow(2).sum().item()
            for parameter, previous in zip(parameters, before)
        )
        return squared_delta ** 0.5

    def _get_entropy_coef(self, iteration=None):
        if iteration is None or self.entropy_anneal_iters <= 0:
            return float(self.entropy_coef)
        if iteration >= self.entropy_anneal_iters:
            return float(self.entropy_coef_end)

        progress = float(iteration) / float(max(self.entropy_anneal_iters, 1))
        return float(
            self.entropy_coef_start
            + (self.entropy_coef_end - self.entropy_coef_start) * progress
        )

    # ------------------------------------------------------------------
    # Context
    # ------------------------------------------------------------------
    def _compute_global_context_dual(self, prev_map, terrain_heat, stats_heat):
        """Encode each generated environment's own previous probe feedback."""
        ctx = self.encoder(prev_map, terrain_heat, stats_heat)
        return F.normalize(ctx, p=2, dim=1)

    # ------------------------------------------------------------------
    # Rollout
    # ------------------------------------------------------------------
    @torch.no_grad()
    def select_action(self, base_map, prev_data, mask, max_edits_layout, max_edits_stats):
        B = base_map.size(0)
        if self.encoder is None:   
            ctx = None
            global_ctx = None
            phs = None
        else:
            if prev_data is None:
                # Initial state: empty map, empty terrain heatmap, empty inventory heatmap.
                H, W = base_map.size(2), base_map.size(3)
                # pm: prev_map, pht: prev_heat_terrain, phs: prev_heat_stats
                pm = torch.zeros((1, 3, H, W), device=device)
                feedback_channels = 2 if self.env_type in ("minigrid", "crafter") else 1
                pht = torch.zeros((1, feedback_channels, H, W), device=device)
                phs = None if self.env_type == "minigrid" else torch.zeros(
                    (1, 26 if self.env_type == "bipedalwalker" else 16), device=device
                )
                global_ctx = self._compute_global_context_dual(pm, pht, phs)
            else:
                if len(prev_data) == 2:
                    pm, pht = prev_data
                    phs = None
                else:
                    pm, pht, phs = prev_data
                global_ctx = self._compute_global_context_dual(pm, pht, phs)
            if global_ctx.size(0) == B:
                ctx = global_ctx
            else:
                ctx = global_ctx.repeat(B, 1)
            if phs is not None and phs.size(0) == 1 and B > 1:
                phs = phs.repeat(B, 1)

        act_result = self.policy_old.act(
            base_map, ctx, mask, max_edits_layout,
            max_stats_edit_ratio=max_edits_stats, stats_heat=phs,
            return_stage_diagnostics=self.env_type == "crafter",
        )
        if self.env_type == "crafter":
            (
                action, stats_act, map_logp, location_logp, stats_logp, value,
                topk_mask, location_order, topk_stats_mask,
                self.last_stage_probabilities, _stage_entropy,
            ) = act_result
        else:
            (
                action, stats_act, map_logp, location_logp, stats_logp, value,
                topk_mask, location_order, topk_stats_mask,
            ) = act_result

        # The fixed-budget MiniGrid action has two learned factors: the
        # ordered location set and the categorical type at each location.
        total_logprob = map_logp.sum(dim=(1, 2)) + location_logp + stats_logp
        self.last_stage_logprob = stats_logp.detach()
        return (
            action, stats_act, total_logprob, value, topk_mask,
            location_order, topk_stats_mask, global_ctx,
        )

    # ------------------------------------------------------------------
    # Buffer
    # ------------------------------------------------------------------
    def save_buffer(
        self, curr_map, prev_data, mask, action, stats_action, logprob, value,
        reward, topk_mask, location_order, stats_topk_mask,
        stage_logprob=None, layout_reward=None, stage_reward=None,
    ):
        self.buffer["curr_map"].append(curr_map.cpu())
        self.buffer["mask"].append(mask.cpu())
        self.buffer["action"].append(action.cpu())
        self.buffer["stats_action"].append(stats_action.cpu())
        self.buffer["logprob"].append(logprob.cpu())
        self.buffer["value"].append(value.cpu())
        self.buffer["reward"].append(float(reward))
        self.buffer["layout_reward"].append(float(reward if layout_reward is None else layout_reward))
        self.buffer["stage_reward"].append(float(reward if stage_reward is None else stage_reward))
        self.buffer["stage_logprob"].append(
            torch.zeros_like(logprob).cpu() if stage_logprob is None else stage_logprob.detach().cpu()
        )
        self.buffer["topk_mask"].append(topk_mask.cpu())
        self.buffer["location_order"].append(location_order.cpu())
        self.buffer["stats_topk_mask"].append(stats_topk_mask.cpu())

        if prev_data is None:
            B, _, H, W = curr_map.shape
            self.buffer["prev_map"].append(torch.zeros((B, 3, H, W)))
            feedback_channels = 2 if self.env_type in ("minigrid", "crafter") else 1
            self.buffer["prev_heat"].append(
                torch.zeros((B, feedback_channels, H, W))
            )
            stats_dim = 26 if self.env_type == "bipedalwalker" else 16
            self.buffer["stats_heat"].append(torch.zeros((B, stats_dim)))
        else:
            if len(prev_data) == 2:
                pm, pht = prev_data
                phs = None
            else:
                pm, pht, phs = prev_data
            self.buffer["prev_map"].append(pm.cpu())
            # We rename prev_heat internally to match dual streams
            self.buffer["prev_heat"].append(pht.cpu())
            if phs is None:
                B = pm.size(0)
                stats_dim = 26 if self.env_type == "bipedalwalker" else 16
                self.buffer["stats_heat"].append(torch.zeros((B, stats_dim)))
            else:
                self.buffer["stats_heat"].append(phs.cpu())
        self.current_round_count += 1

    def clear_buffer(self):
        for k in self.buffer:
            self.buffer[k].clear()
        self.round_lengths.clear()
        self.current_round_count = 0

    def _trim_buffer_to_recent_rounds(self):
        while len(self.round_lengths) > self.buffer_window_rounds:
            remove_n = int(self.round_lengths.popleft())
            if remove_n <= 0:
                continue
            for k in self.buffer:
                if remove_n >= len(self.buffer[k]):
                    self.buffer[k].clear()
                else:
                    del self.buffer[k][:remove_n]

    # ------------------------------------------------------------------
    # PPO Update
    # ------------------------------------------------------------------
    def update(self, iteration=None):
        """Update from complete, on-policy rollout rounds.

        The public return value remains ``(loss, entropy)``.  Detailed values
        are exposed through ``last_diagnostics`` so existing callers do not
        need to change when diagnostic logging is enabled.
        """
        self.last_diagnostics = self._empty_diagnostics()
        if len(self.buffer["curr_map"]) == 0:
            print("[GeneratorPPO] Warning: Buffer is empty, skipping update.")
            return 0.0, 0.0

        if self.current_round_count > 0:
            self.round_lengths.append(self.current_round_count)
            self.current_round_count = 0

        round_count = len(self.round_lengths)
        sample_count = len(self.buffer["reward"])
        self.last_diagnostics.update({
            "sample_count": sample_count,
            "round_count": round_count,
        })
        if round_count < self.update_every_rounds:
            # policy_old remains frozen while this rollout batch is assembled.
            return 0.0, 0.0

        # An update consumes all retained samples.  Under normal operation this
        # is exactly update_every_rounds rounds; retaining extras would mix
        # samples with a policy that will be changed by this update.
        if round_count != self.update_every_rounds:
            raise RuntimeError(
                "GeneratorPPO received more rollout rounds than update_every_rounds "
                f"({round_count} > {self.update_every_rounds})."
            )

        split_active = (
            self.env_type == "crafter"
            and self.crafter_credit_mode in {"split", "split_balanced_global"}
            and iteration is not None and iteration >= self.warmup_iterations
        )
        raw_rewards = torch.tensor(self.buffer["reward"], device=device)
        raw_stage_rewards = torch.tensor(self.buffer["stage_reward"], device=device)
        stage_reward_std = raw_stage_rewards.std(unbiased=False).item() if len(raw_stage_rewards) > 1 else 0.0
        if split_active and (len(raw_stage_rewards) != len(raw_rewards) or len(self.buffer["stage_logprob"]) != len(raw_rewards)):
            raise ValueError("Crafter split credit requires one stage reward and log probability per rollout")
        self.last_mean_reward = raw_rewards.mean().item()
        current_entropy_coef = self._get_entropy_coef(iteration)
        self.last_entropy_coef = current_entropy_coef
        print(f"[GeneratorPPO] Mean Reward: {self.last_mean_reward:.4f}")
        print(f"[GeneratorPPO] Entropy Coef: {current_entropy_coef:.4f}")
        print(
            f"[GeneratorPPO] Updating {round_count} round(s), {sample_count} samples"
        )

        rewards = raw_rewards.clone()
        reward_std = rewards.std(unbiased=False).item() if len(rewards) > 1 else 0.0
        if len(rewards) > 1 and reward_std > 1e-4:
            rewards = (rewards - rewards.mean()) / (rewards.std() + 1e-8)

        curr_map = torch.cat(self.buffer["curr_map"]).to(device)
        mask = torch.cat(self.buffer["mask"]).to(device)
        action = torch.cat(self.buffer["action"]).to(device)
        stats_action = torch.cat(self.buffer["stats_action"]).to(device)
        old_logprob = torch.cat(self.buffer["logprob"]).to(device)
        if split_active:
            old_stage_logprob = torch.cat(self.buffer["stage_logprob"]).to(device)
            old_layout_logprob = old_logprob - old_stage_logprob
            if len(raw_stage_rewards) > 1 and stage_reward_std > 1e-4:
                stage_advantages = (raw_stage_rewards - raw_stage_rewards.mean()) / (stage_reward_std + 1e-8)
            else:
                stage_advantages = torch.zeros_like(raw_stage_rewards)
        old_value = torch.cat(self.buffer["value"]).to(device).reshape(-1)
        topk_mask = torch.cat(self.buffer["topk_mask"]).to(device)
        location_order = torch.cat(self.buffer["location_order"]).to(device)
        stats_topk_mask = torch.cat(self.buffer["stats_topk_mask"]).to(device)
        prev_map = torch.cat(self.buffer["prev_map"]).to(device)
        prev_heat_terrain = torch.cat(self.buffer["prev_heat"]).to(device)
        prev_heat_stats = torch.cat(self.buffer["stats_heat"]).to(device)

        advantages = rewards - old_value.detach()
        advantage_std = advantages.std(unbiased=False).item() if len(advantages) > 1 else 0.0
        if len(advantages) > 1 and advantage_std > 1e-4:
            advantages = (advantages - advantages.mean()) / (advantages.std() + 1e-8)

        parameter_before = self._parameter_snapshot()
        last_metrics = None
        initial_logprob_max_error = 0.0
        initial_layout_logprob_max_error = 0.0
        initial_stage_logprob_max_error = 0.0
        shared_gradient_cosine = float("nan")
        shared_layout_gradient_norm = float("nan")
        shared_stage_gradient_norm = float("nan")
        stage_head_policy_gradient_norm = float("nan")
        stage_head_parameters = list(self.policy.stats_actor.parameters()) if split_active else []
        stage_head_before = [parameter.detach().clone() for parameter in stage_head_parameters]
        stage_pre_prob_parts = []
        stage_pre_entropy_parts = []
        stage_context_parts = []
        stage_diagnostic_ranges = []
        stage_policy_kl_pre_post = float("nan")
        stage_entropy_pre = float("nan")
        stage_entropy_post = float("nan")
        shared_actor_parameters = self._crafter_shared_actor_parameters() if split_active else []
        for epoch in range(self.K_epochs):
            # Evaluate each rollout round with the same batch shape used when
            # its log-probability was collected. This avoids harmless but
            # measurable batch-size-dependent floating-point differences in
            # convolution kernels when update_every_rounds > 1.
            round_ranges = []
            offset = 0
            if self.is_minigrid or self.env_type == "crafter":
                for round_length in self.round_lengths:
                    end = offset + int(round_length)
                    round_ranges.append((offset, end))
                    offset = end
            if not round_ranges or offset != curr_map.size(0):
                round_ranges = [(0, curr_map.size(0))]

            eval_parts = []
            entropy_parts = []
            for start, end in round_ranges:
                if self.encoder is None:
                    ctx_part = None
                else:
                    ctx_part = self._compute_global_context_dual(
                        prev_map[start:end],
                        prev_heat_terrain[start:end],
                        prev_heat_stats[start:end],
                    )
                    if ctx_part.size(0) != end - start:
                        ctx_part = ctx_part.repeat(end - start, 1)

                stage_diagnostics_requested = split_active and epoch == 0
                evaluation = self.policy.evaluate(
                    curr_map[start:end],
                    ctx_part,
                    (action[start:end], stats_action[start:end]),
                    mask[start:end],
                    target_topk_mask=topk_mask[start:end],
                    target_location_order=location_order[start:end],
                    target_stats_topk_mask=stats_topk_mask[start:end],
                    stats_heat=prev_heat_stats[start:end],
                    return_stage_diagnostics=stage_diagnostics_requested,
                )
                eval_parts.append(evaluation[:5])
                entropy_parts.append(eval_parts[-1][-1])
                if stage_diagnostics_requested:
                    stage_pre_prob_parts.append(evaluation[5])
                    stage_pre_entropy_parts.append(evaluation[6])
                    stage_context_parts.append(
                        ctx_part.detach() if torch.is_tensor(ctx_part) else None
                    )
                    stage_diagnostic_ranges.append((start, end))

            logp_terrain = torch.cat([part[0] for part in eval_parts], dim=0)
            logp_location = torch.cat([part[1] for part in eval_parts], dim=0)
            logp_stats = torch.cat([part[2] for part in eval_parts], dim=0)
            value = torch.cat([part[3] for part in eval_parts], dim=0)
            entropy = sum(
                part * (end - start)
                for part, (start, end) in zip(entropy_parts, round_ranges)
            ) / max(curr_map.size(0), 1)
            total_logp = logp_terrain.sum(dim=(1, 2)) + logp_location + logp_stats
            value = value.reshape(-1)
            logprob_delta = total_logp - old_logprob.detach()
            if epoch == 0:
                # Validate the actual on-policy invariant: the probability
                # recomputed before the first optimizer step must match the
                # value saved during rollout. Comparing policy and policy_old
                # on one newly-computed context would hide context drift.
                initial_logprob_max_error = torch.abs(
                    total_logp.detach() - old_logprob.detach()
                ).max().item()
            ratio = torch.exp(logprob_delta)
            if split_active:
                layout_logp = logp_terrain.sum(dim=(1, 2)) + logp_location
                layout_delta = layout_logp - old_layout_logprob.detach()
                stage_delta = logp_stats - old_stage_logprob.detach()
                if epoch == 0:
                    initial_layout_logprob_max_error = layout_delta.detach().abs().max().item()
                    initial_stage_logprob_max_error = stage_delta.detach().abs().max().item()
                layout_ratio = torch.exp(layout_delta)
                stage_ratio = torch.exp(stage_delta)
                loss_layout_policy = -torch.min(
                    layout_ratio * advantages,
                    torch.clamp(layout_ratio, 1 - self.eps_clip, 1 + self.eps_clip) * advantages,
                ).mean()
                loss_stage_policy = -torch.min(
                    stage_ratio * stage_advantages,
                    torch.clamp(stage_ratio, 1 - self.eps_clip, 1 + self.eps_clip) * stage_advantages,
                ).mean()
                loss_policy = loss_layout_policy + loss_stage_policy
                if epoch == 0 and shared_actor_parameters:
                    layout_shared_grads = torch.autograd.grad(
                        loss_layout_policy,
                        shared_actor_parameters,
                        retain_graph=True,
                        allow_unused=True,
                    )
                    stage_shared_grads = torch.autograd.grad(
                        loss_stage_policy,
                        shared_actor_parameters,
                        retain_graph=True,
                        allow_unused=True,
                    )
                    (
                        shared_gradient_cosine,
                        shared_layout_gradient_norm,
                        shared_stage_gradient_norm,
                    ) = self._shared_gradient_similarity(layout_shared_grads, stage_shared_grads)
                    stage_head_grads = torch.autograd.grad(
                        loss_stage_policy,
                        stage_head_parameters,
                        retain_graph=True,
                        allow_unused=True,
                    )
                    stage_head_policy_gradient_norm = self._gradient_list_norm(
                        stage_head_grads
                    )
            else:
                surr1 = ratio * advantages
                surr2 = torch.clamp(ratio, 1 - self.eps_clip, 1 + self.eps_clip) * advantages
                loss_policy = -torch.min(surr1, surr2).mean()
                loss_layout_policy = loss_policy
                loss_stage_policy = torch.zeros_like(loss_policy)
            loss_value = 0.5 * self.mse(value, rewards)
            loss_entropy = -current_entropy_coef * entropy.mean()
            total_loss = loss_policy + loss_value + loss_entropy

            if not torch.isfinite(total_loss):
                print(f"[GeneratorPPO] Warning: non-finite loss in epoch {epoch}; clearing rollout.")
                self.clear_buffer()
                return 0.0, 0.0

            self.optimizer.zero_grad()
            total_loss.backward()
            preclip_grad_norm = self._gradient_norm()
            torch.nn.utils.clip_grad_norm_(self.policy.parameters(), 0.5)
            if self.encoder is not None:
                torch.nn.utils.clip_grad_norm_(self.encoder.parameters(), 0.5)
            self.optimizer.step()

            last_metrics = {
                "policy_loss": loss_policy.item(),
                "layout_policy_loss": loss_layout_policy.item(),
                "stage_policy_loss": loss_stage_policy.item(),
                "value_loss": loss_value.item(),
                "entropy_loss": loss_entropy.item(),
                "total_loss": total_loss.item(),
                "ratio_mean": ratio.mean().item(),
                "ratio_min": ratio.min().item(),
                "ratio_max": ratio.max().item(),
                "approx_kl": (-logprob_delta).mean().item(),
                "clip_fraction": (torch.abs(ratio - 1.0) > self.eps_clip).float().mean().item(),
                "preclip_grad_norm": preclip_grad_norm,
            }
        parameter_delta = self._parameter_delta(parameter_before)
        if split_active:
            stage_head_parameter_delta = self._parameter_list_delta(
                stage_head_parameters, stage_head_before
            )
            with torch.no_grad():
                stage_post_prob_parts = []
                stage_post_entropy_parts = []
                for (start, end), ctx_part in zip(
                    stage_diagnostic_ranges, stage_context_parts
                ):
                    edited_map = self.policy._crafter_materialize_layout(
                        curr_map[start:end], action[start:end]
                    )
                    stage_logits = self.policy._crafter_stage_logits(
                        edited_map, ctx_part, prev_heat_stats[start:end]
                    )
                    stage_dist = Categorical(logits=stage_logits)
                    stage_post_prob_parts.append(stage_dist.probs)
                    stage_post_entropy_parts.append(
                        stage_dist.entropy().reshape(end - start, -1).mean(dim=-1)
                    )
                pre_probs = torch.cat(stage_pre_prob_parts, dim=0)
                post_probs = torch.cat(stage_post_prob_parts, dim=0)
                pre_log_probs = torch.log(pre_probs.clamp_min(1e-8))
                post_log_probs = torch.log(post_probs.clamp_min(1e-8))
                stage_policy_kl_pre_post = float(
                    (pre_probs * (pre_log_probs - post_log_probs))
                    .sum(dim=-1)
                    .mean()
                    .clamp_min(0.0)
                    .item()
                )
                stage_entropy_pre = float(
                    torch.cat(stage_pre_entropy_parts, dim=0).mean().item()
                )
                stage_entropy_post = float(
                    torch.cat(stage_post_entropy_parts, dim=0).mean().item()
                )
        else:
            stage_head_parameter_delta = float("nan")
        self.policy_old.load_state_dict(self.policy.state_dict())
        self.clear_buffer()

        self.last_diagnostics.update(last_metrics)
        if split_active and shared_gradient_cosine == shared_gradient_cosine:
            conflict = int(shared_gradient_cosine < 0.0)
            self._shared_actor_gradient_conflict_updates += conflict
            self._shared_actor_gradient_measure_count += 1
            conflict_ratio = (
                self._shared_actor_gradient_conflict_updates
                / self._shared_actor_gradient_measure_count
            )
        else:
            conflict = float("nan")
            conflict_ratio = float("nan")
        self.last_diagnostics.update({
            "updated": True,
            "sample_count": sample_count,
            "round_count": round_count,
            "reward_std": reward_std,
            "advantage_std": advantage_std,
            "parameter_delta": parameter_delta,
            "initial_logprob_max_error": initial_logprob_max_error,
            "initial_layout_logprob_max_error": initial_layout_logprob_max_error,
            "initial_stage_logprob_max_error": initial_stage_logprob_max_error,
            "stage_reward_mean": raw_stage_rewards.mean().item(),
            "stage_reward_std": stage_reward_std,
            "shared_actor_gradient_cosine": shared_gradient_cosine,
            "shared_actor_gradient_conflict": conflict,
            "shared_actor_gradient_conflict_ratio": conflict_ratio,
            "shared_layout_gradient_norm": shared_layout_gradient_norm,
            "shared_stage_gradient_norm": shared_stage_gradient_norm,
            "stage_head_policy_gradient_norm": stage_head_policy_gradient_norm,
            "stage_head_parameter_delta": stage_head_parameter_delta,
            "stage_policy_kl_pre_post": stage_policy_kl_pre_post,
            "stage_entropy_pre": stage_entropy_pre,
            "stage_entropy_post": stage_entropy_post,
        })
        return last_metrics["total_loss"], entropy.mean().item()

    # ------------------------------------------------------------------
    # Save / Load
    # ------------------------------------------------------------------
    def save(self, path):
        save_dict = {"policy": self.policy.state_dict()}
        if self.encoder is not None:
            save_dict["encoder"] = self.encoder.state_dict()
        torch.save(save_dict, path)

    def load(self, path):
        ckpt = torch.load(path, map_location=device)
        self.policy.load_state_dict(ckpt["policy"])
        self.policy_old.load_state_dict(ckpt["policy"])
        if self.encoder is not None and "encoder" in ckpt:
            self.encoder.load_state_dict(ckpt["encoder"])
