# trainer/conf/config_dr.yaml
# Unified Domain Randomization (DR) Baseline Configuration

defaults:
  - config_mac                 # Inherit WM, EWC, Buffer from unified config
  - _self_

# --- Control Switch ---
domain: 'crafter'             # Options: 'crafter' or 'minigrid'

# --- Force Random Exploration (DR core) ---
generator_agent:
  agent_type: 'random'         # No adversarial, just random maps
  total_iterations: 50
  wm_train_frequency: 1
  warmup_iterations: 0         # No need to warm up random

# --- Domain-Specific Overrides ---
domains:
  crafter:
    val_n_phases: 20 # might need to add more after the trail testing
    val_task_prefix: "crafter_target_task_"
    val_data_path: ${domains.crafter.target_tasks_folder}
    val_suffix: "_uniform.npz"
    grid_shape: [2, 31, 31]
    obs_norm: [20, 5, 0]
    action_norm: 17
    start_idx: 1
    
  minigrid:
    val_n_phases: 20
    val_task_prefix: "target_task"
    val_data_path: ${domains.minigrid.target_tasks_folder}
    val_suffix: "_test_uniform.npz"
    grid_shape: [3, 0, 0]
    obs_norm: [10, 5, 3]
    action_norm: 7
    start_idx: 0

# Logger settings
dr_log_dir: ${oc.env:TRAINER_PATH}/logs/results_dr/
dr_temp_data_dir: ${domains.${domain}.mini_tasks_temp_root}dr/
seed: 0
