# Crafter Continual Learning Configuration
attention_model:
  env_type: crafter
  data_type: discrete
  model_type: Attention
  grid_shape: [2, 0, 0]  # Crafter=2 channels (object + direction)
  attention_mask_size: 5
  batch_size: 512
  n_cpu: 8
  embed_dim: 256
  num_heads: 4
  # Default directory, will be overridden in the script
  data_dir: ${oc.env:TRAIN_DATASET_PATH}/crafter_minitask_01.npz
  validation_data_dir: ${oc.env:TRAIN_DATASET_PATH}/crafter_target_uniform_test.npz
  max_train_samples: 20000
  n_epochs: 15
  lr: 8e-4
  wd: 1e-4
  obs_norm_values: [10, 5, 3] # Overridden in code for crafter
  action_norm_values: 5 
  valid_values_obj: [1, 2, 4, 5, 8, 10]
  valid_values_color: [0, 1, 5]
  valid_values_state: [0, 1, 2, 3]
  use_wandb: False
  frame_stack: 1

  # Model saving
  freeze_weight: False
  model_save_path: ${oc.env:MODEL_FPATH}/AttentionWM/attention_world_model_crafter_CL.ckpt

  # Continual Learning / EWC Params
  continue_learning: True
  lambda_ewc: 200.0 # higher to protect the old knowledge      
  ewc_ratio: 0.05           
  lambda_ema: 0.1
  lambda_ewc_min: 0.1
  lambda_ewc_max: 10000.0
  scale_factor: 1.0
  replay_frac: 0.7
  fisher_buffer_size: 500000
  fisher_buffer_elements_ratio: 0.8
  fisher_beta: 0.7 # 0.3 -> 0.5: Standard update speed (smaller -> faster)

  # Visualization
  visualization: True     
  visualize_every: 50
  save_path: ${oc.env:PROJECT_ROOT}/modelBased/visulization
  direction_map: {0: 'right', 1: 'down', 2: 'left', 3: 'up'}
  action_map: {0: 'left', 1: 'right', 2: 'forward', 3: 'pickup', 4: 'toggle'}

env:
  env_type: crafter
  visualize: False
  collect:
    data_type: random
    episodes: 500
    mini_dataset_size: 8000
    maximum_dataset_size: 20000
    data_save_path: ${oc.env:TRAIN_DATASET_PATH}/crafter_minitask_01.npz
    save_coverage_visualize: True
    visualize_save_path: ${oc.env:PROJECT_ROOT}/trainer/logs/dataset_visualization
    visualize_filename: crafter_minitask_01_random_coverage.png
    save_env_visualize: True
    env_visualize_save_path: ${oc.env:PROJECT_ROOT}/trainer/logs/env_visualization
    env_visualize_filename: crafter_minitask_01_random_env.png


