# trainer/conf/config_dr.yaml
# Unified Domain Randomization (DR) Baseline Configuration

defaults:
  - config_mac                 # Inherit WM, EWC, Buffer from unified config
  - _self_

# --- Control Switch ---
domain: 'minigrid'             # Options: 'crafter' or 'minigrid' or 'bipedal'

# --- Force Random Exploration (DR core) ---
generator_agent:
  agent_type: 'random'         # No adversarial, just random maps
  total_iterations: 40 # 30 minigrid 50 bipedal 
  wm_train_frequency: 1
  warmup_iterations: 0         # No need to warm up random

# Logger settings
dr_log_dir: ${oc.env:TRAINER_PATH}/logs/results_dr/
dr_temp_data_dir: ${domains.${domain}.mini_tasks_temp_root}dr/
seed: 4
force_fresh_start: true         # Set to true to delete old model and start from scratch
